use std::fs;
use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::Parser;
use ignore::WalkBuilder;
use ignore::overrides::{Override, OverrideBuilder};
use tracing::{debug, info, warn};

use crate::github_api::GithubApi;
use crate::parser::{
    is_sha, is_short_sha, is_version_like_ref, parse_comment_ref, parse_quote, parse_repo_ref,
    parse_uses_line, replace_ref,
};

#[derive(Debug, Parser)]
#[command(name = "act-up")]
#[command(author = clap::crate_authors!())]
#[command(version = clap::crate_version!())]
#[command(about = clap::crate_description!(), long_about = None)]
#[command(after_help = r#"Examples:
  - Update all workflow files in current directory: `act-up`
  - Update all workflow files other than deploy.yml: `act-up --files !.github/workflows/deploy.yml`
  - Preview changes without writing to files: `act-up --dry-run`

Notes:
  - If you hit GitHub API rate limit, you can set `GITHUB_TOKEN` environment variable to a personal access token.
  - Non-semver refs (e.g. `main`) won't be updated unless --pin is set.
  - If the first line contains `autogenerated` or `auto generated`, the file is skipped."#)]
struct Cli {
    /// Extra gitignore-like file globs merged with defaults. Use `!` prefix to exclude.
    #[arg(long, value_delimiter = ',')]
    files: Vec<String>,

    /// Preview changes only. By default, act-up writes updates to files.
    #[arg(long)]
    dry_run: bool,

    /// Force pin refs to commit SHA for non-pinned actions.
    #[arg(long)]
    pin: bool,
}

const DEFAULT_FILE_PATTERNS: [&str; 2] = [".github/workflows/*.yml", ".github/workflows/*.yaml"];
const GENERATED_FILE_INDICATORS: [&str; 3] = ["autogenerated", "auto generated", "@generated"];

#[derive(Debug, Clone)]
struct ChangeRecord {
    line_no: usize,
    repo: String,
    old_ref: String,
    new_ref: String,
    pinned: bool,
}

pub fn run() -> Result<()> {
    let cli = Cli::parse();
    let file_patterns = merged_file_patterns(&cli.files);
    let files = collect_yaml_files(&file_patterns)?;

    if files.is_empty() {
        warn!("no files matching given patterns");
        return Ok(());
    }
    info!("checking {} files", files.len());

    let mut api = GithubApi::new()?;
    let mut all_changes = Vec::new();

    for file in files {
        let content = fs::read_to_string(&file)
            .with_context(|| format!("failed reading {}", file.display()))?;
        if is_generated_file(&content) {
            debug!("skipped generated: {}", file.display());
            continue;
        }

        let (new_content, line_changes) = update_file_content(&mut api, &content, cli.pin)?;

        if line_changes.is_empty() {
            continue;
        }

        for change in &line_changes {
            info!(
                "{}: {}:{} {}@{} -> {}{}",
                if cli.dry_run {
                    "would update"
                } else {
                    "updated"
                },
                file.display(),
                change.line_no,
                change.repo,
                change.old_ref,
                change.new_ref,
                if change.pinned { " (pinned)" } else { "" }
            );
        }

        all_changes.extend(line_changes);

        if !cli.dry_run {
            fs::write(&file, new_content)
                .with_context(|| format!("failed writing {}", file.display()))?;
        }
    }

    if all_changes.is_empty() {
        info!("completed: no updates");
    } else {
        let mut messages = vec!["completed:".to_string()];
        for change in &all_changes {
            messages.push(format!(
                "      - {}@{} -> {}{}",
                change.repo,
                change.old_ref,
                change.new_ref,
                if change.pinned { " (pinned)" } else { "" }
            ));
        }
        info!("{}", messages.join("\n"));
    }

    if cli.dry_run && !all_changes.is_empty() {
        info!("re-run without --dry-run to apply changes");
    }

    Ok(())
}

fn collect_yaml_files(patterns: &[String]) -> Result<Vec<PathBuf>> {
    let overrides = compile_file_overrides(patterns)?;
    let mut files = Vec::new();

    for entry in WalkBuilder::new(".")
        .follow_links(false)
        .hidden(false)
        .ignore(false)
        .git_ignore(false)
        .git_global(false)
        .git_exclude(false)
        .parents(false)
        .overrides(overrides)
        .build()
        .filter_map(std::result::Result::ok)
    {
        let path = entry.path();
        if !entry.file_type().is_some_and(|kind| kind.is_file()) {
            continue;
        }

        files.push(path.to_path_buf());
    }

    files.sort();
    files.dedup();
    Ok(files)
}

fn merged_file_patterns(cli_patterns: &[String]) -> Vec<String> {
    let mut merged = DEFAULT_FILE_PATTERNS
        .iter()
        .map(|p| (*p).to_string())
        .collect::<Vec<_>>();

    for pattern in cli_patterns {
        let trimmed = pattern.trim();
        if trimmed.is_empty() {
            continue;
        }
        merged.push(trimmed.to_string());
    }

    merged
}

fn compile_file_overrides(patterns: &[String]) -> Result<Override> {
    let mut builder = OverrideBuilder::new(".");

    for pattern in patterns {
        let trimmed = pattern.trim();
        if trimmed.is_empty() {
            continue;
        }

        builder
            .add(trimmed)
            .with_context(|| format!("invalid --files glob pattern: {trimmed}"))?;
    }

    builder
        .build()
        .with_context(|| "failed building --files overrides".to_string())
}

fn is_generated_file(content: &str) -> bool {
    let first = content
        .lines()
        .next()
        .unwrap_or_default()
        .to_ascii_lowercase();
    GENERATED_FILE_INDICATORS
        .iter()
        .any(|indicator| first.contains(indicator))
}

fn update_file_content(
    api: &mut GithubApi,
    content: &str,
    pin: bool,
) -> Result<(String, Vec<ChangeRecord>)> {
    let mut changes = Vec::new();

    let has_trailing_newline = content.ends_with('\n');
    let mut output_lines = Vec::new();

    for (idx, line) in content.lines().enumerate() {
        if let Some((new_line, change)) = maybe_update_uses_line(api, line, pin)? {
            if new_line != line {
                if let Some(mut record) = change {
                    record.line_no = idx + 1;
                    changes.push(record);
                }
            } else if change.is_some() {
                // Parsed uses line, but effective result is unchanged.
                debug!(line, "line parsed but unchanged");
            }
            output_lines.push(new_line);
        } else {
            output_lines.push(line.to_string());
        }
    }

    let mut new_content = output_lines.join("\n");
    if has_trailing_newline {
        new_content.push('\n');
    }

    Ok((new_content, changes))
}

fn maybe_update_uses_line(
    api: &mut GithubApi,
    line: &str,
    pin: bool,
) -> Result<Option<(String, Option<ChangeRecord>)>> {
    let parsed = match parse_uses_line(line) {
        Some(v) => v,
        None => return Ok(None),
    };

    let parsed_quote = parse_quote(&parsed.value_raw);
    let repo_ref = match parse_repo_ref(parsed_quote.value) {
        Some(v) => v,
        None => return Ok(Some((line.to_string(), None))),
    };

    if repo_ref.hostname != "github.com" {
        debug!(line, "skipping non-github uses line");
        return Ok(Some((line.to_string(), None)));
    }

    let comment_body = parsed.comment_suffix.strip_prefix(" #").unwrap_or_default();
    let is_pinned_digest = is_sha(repo_ref.current_ref) || is_short_sha(repo_ref.current_ref);
    let mut resolved_comment_ref: Option<String> = None;

    debug!(
        owner = repo_ref.owner,
        repo = repo_ref.repo,
        current_ref = repo_ref.current_ref,
        comment_body,
        pin,
        is_pinned_digest,
        "processing uses line"
    );

    if is_pinned_digest {
        let Some(target_ref) = parse_comment_ref(comment_body) else {
            debug!("skipping pinned digest line without parseable comment ref");
            return Ok(Some((line.to_string(), None)));
        };

        let effective_target_ref = if is_version_like_ref(&target_ref) {
            match api.resolve_updated_ref(repo_ref.owner, repo_ref.repo, &target_ref)? {
                Some(updated_ref) => {
                    debug!(
                        target_ref = %target_ref,
                        updated_ref = %updated_ref,
                        "resolved newer version-like comment ref"
                    );
                    updated_ref
                }
                None => target_ref.clone(),
            }
        } else {
            target_ref.clone()
        };

        resolved_comment_ref = Some(effective_target_ref.clone());
        let new_sha = api.resolve_ref_sha(repo_ref.owner, repo_ref.repo, &effective_target_ref)?;
        debug!(
            target_ref = %effective_target_ref,
            new_sha = %new_sha,
            "resolved pinned digest target sha"
        );

        if new_sha == repo_ref.current_ref {
            debug!("resolved sha matches current sha, skipping line update");
            return Ok(Some((line.to_string(), None)));
        }

        let replacement_ref = new_sha;
        let replaced = replace_ref(parsed_quote.value, replacement_ref.as_str());
        let rebuilt_value = if parsed_quote.quote.is_empty() {
            replaced
        } else {
            format!("{}{}{}", parsed_quote.quote, replaced, parsed_quote.quote)
        };

        let final_comment = if let Some(comment_ref) = resolved_comment_ref {
            format!(" # {}", comment_ref)
        } else if pin && !is_pinned_digest && parsed.comment_suffix.is_empty() {
            format!(" # {}", repo_ref.current_ref)
        } else {
            parsed.comment_suffix
        };

        let record = Some(ChangeRecord {
            line_no: 0,
            repo: format!("{}/{}", repo_ref.owner, repo_ref.repo),
            old_ref: target_ref,
            new_ref: effective_target_ref.clone(),
            pinned: true,
        });

        Ok(Some((
            format!("{}{}{}", parsed.prefix, rebuilt_value, final_comment),
            record,
        )))
    } else if pin {
        let pinned_sha =
            api.resolve_ref_sha(repo_ref.owner, repo_ref.repo, repo_ref.current_ref)?;
        if pinned_sha == repo_ref.current_ref {
            debug!("--pin resolved same sha, skipping line update");
            return Ok(Some((line.to_string(), None)));
        }

        let replacement_ref = pinned_sha;
        let replaced = replace_ref(parsed_quote.value, replacement_ref.as_str());
        let rebuilt_value = if parsed_quote.quote.is_empty() {
            replaced
        } else {
            format!("{}{}{}", parsed_quote.quote, replaced, parsed_quote.quote)
        };

        let final_comment = if let Some(comment_ref) = resolved_comment_ref {
            format!(" # {}", comment_ref)
        } else if pin && !is_pinned_digest && parsed.comment_suffix.is_empty() {
            format!(" # {}", repo_ref.current_ref)
        } else {
            parsed.comment_suffix
        };

        let record = Some(ChangeRecord {
            line_no: 0,
            repo: format!("{}/{}", repo_ref.owner, repo_ref.repo),
            old_ref: repo_ref.current_ref.to_string(),
            new_ref: repo_ref.current_ref.to_string(),
            pinned: true,
        });

        Ok(Some((
            format!("{}{}{}", parsed.prefix, rebuilt_value, final_comment),
            record,
        )))
    } else {
        if !is_version_like_ref(repo_ref.current_ref) {
            debug!("skipping non-semver textual ref without --pin");
            return Ok(Some((line.to_string(), None)));
        }

        match api.resolve_updated_ref(repo_ref.owner, repo_ref.repo, repo_ref.current_ref)? {
            Some(updated_ref) if updated_ref != repo_ref.current_ref => {
                let replacement_ref = updated_ref.clone();
                let replaced = replace_ref(parsed_quote.value, replacement_ref.as_str());
                let rebuilt_value = if parsed_quote.quote.is_empty() {
                    replaced
                } else {
                    format!("{}{}{}", parsed_quote.quote, replaced, parsed_quote.quote)
                };

                let final_comment = if let Some(comment_ref) = resolved_comment_ref {
                    format!(" # {}", comment_ref)
                } else if pin && !is_pinned_digest && parsed.comment_suffix.is_empty() {
                    format!(" # {}", repo_ref.current_ref)
                } else {
                    parsed.comment_suffix
                };

                let record = Some(ChangeRecord {
                    line_no: 0,
                    repo: format!("{}/{}", repo_ref.owner, repo_ref.repo),
                    old_ref: repo_ref.current_ref.to_string(),
                    new_ref: updated_ref,
                    pinned: false,
                });

                Ok(Some((
                    format!("{}{}{}", parsed.prefix, rebuilt_value, final_comment),
                    record,
                )))
            }
            _ => {
                debug!("no newer textual ref found");
                Ok(Some((line.to_string(), None)))
            }
        }
    }
}
