name: autofix.ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]


jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      - run: rustup component add clippy rustfmt
      - run: cargo test
      - run: cargo fmt
      - run: cargo clippy --fix --allow-dirty --allow-staged --all-targets --all-features -- -D warnings
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
        if: ${{ always() }}
        with:
          commit-message: "style: fix"
